### ISSUE TITLE
Using clojure.exe / clj.exe via custom-path installation appears problematic

### ISSUE THREAD

**Issue by sogaiu** [frericksm/clj-windows#7]
I used the installation method involving specifying a custom path, e.g.:

```
install.exe C:\Users\bob\bin
```

but experienced difficulty using clojure.exe from such an installation.

Execution of clojure.exe from within C:\Users\bob\bin\clojure\lib works, but when attempted in some other directories (e.g. from within a freshly cloned clojure-project repository such as https://github.com/borkdude/clj-kondo), I get error messages similar to:

```
Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main
... open .cpcache/ec67dd60.cp: The system cannot find the path specified.
```

If I uninstall and reinstall without specifying a custom path, clojure.exe works appropriately.

In any case, thanks for providing this tool :)

**Comment by frericksm** [comment]
good catch. thanks . Will be fixed in next release.

**Comment by sogaiu** [comment]
Thanks!
