### ISSUE TITLE
Upstream clojure tools 1.10.1.458 available

### ISSUE THREAD

**Issue by sogaiu** [frericksm/clj-windows#9]
According to the [changelog](https://github.com/clojure/tools.deps.alpha/blob/master/CHANGELOG.md), it looks like at least the following has changed:

0.7.516 on June 29, 2019

    Add ctda.reader/default-deps to duplicate the deps.edn file logic in clj

0.7.511 on June 29, 2019

    Fix regression on default clojure version in install

0.7.505 on June 28, 2019

    TDEPS-52 Embed install deps.edn, fix path gen on deps with no paths
    TDEPS-96 Generate pom source path relative to transitive root dir
    TDEPS-88 Resolve meaning of -Srepro (include install deps, ignore ~/.clojure)

**Comment by frericksm** [comment]
fixed in https://github.com/frericksm/clj-windows/releases/tag/1.10.1.458
